### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by hjlftech** [dwp-forge/columns#3]
Updated my dokuwiki to Detritus and the whole site didn't work. Tested plugins one by one and found /?Columns to be the culprit.  Download the lates version of plugin and site worked again. However, the columns function did **not** work.

The columns 'markup' is just showing as text in the viewed page...???

![columns](https://cloud.githubusercontent.com/assets/18195769/14186061/6a9edbb8-f774-11e5-8595-abd9d81a56b5.jpg)

**Comment by dwp-forge** [comment]
Just checked on a fresh Detritus install -- it seems to work as expected.

![detrius](https://cloud.githubusercontent.com/assets/11460562/14199567/34d0f85c-f7ee-11e5-8b22-49ca5938b882.png)

Could that be a caching problem or combination with some other plugin?

**Comment by hjlftech** [comment]
Peculiar!

I don't think it would be a plugin issue, as columns is the only 
non-standard plugin I have.

Interestingly, I changed the theme of the wiki (to 'Simple' theme) and 
the columns worked.  I then changed the theme back to the default 
Dokuwiki theme...and now the columns worked in that theme, too, although 
originally they hadn't.  ??

Very confusing!  I suspect an internal dokuwiki caching issue which is 
beyond my abilities to identify!

So it's working now, although it might be a small problem for people 
updating DW over existing data or using different themes. Something to 
watch, perhaps.

Thanks for getting back promptly.

regards

**Comment by dwp-forge** [comment]
[Caching](https://www.dokuwiki.org/caching) is a known problem when doing somewhat advanced stuff in DokuWiki. When in doubt just delete all subdirectories of `data/cache/` and then you know for sure that you start from scratch.

**Comment by hjlftech** [comment]
Thanks for the tip, MYkola, will take note of that!   All seems to be well again with the page, cheers.

![screen shot 2016-04-01 at 19 41 11](https://cloud.githubusercontent.com/assets/18195769/14216655/ea059694-f841-11e5-82b4-d219518aca80.png)
