### ISSUE TITLE
Table inside column causes table heading to be displayed multiple times

### ISSUE THREAD

**Issue by gogglespisano** [dwp-forge/columns#7]
If a table is put inside a column, the table element used to display columns replicates the header row of the embedded table to the columns table and adds a duplicate to the embedded table.

**Comment by dwp-forge** [comment]
I see no issues with table rendering using the following example:
```
<columns 100% 50% ->

Column 1

^ Text 1 ^ Text 2 ^
| 100    | 200    |

<newcolumn>

Column 2

^ Text 1 ^ Text 2 ^
| 100    | 200    |

</columns>
```

![image](https://github.com/dwp-forge/columns/assets/11460562/afceaf3e-28cd-49d6-b285-2b0f59ad2c43)

Could you please provide an example DokuWiki text to reproduce the issue?
