### ISSUE TITLE
Columns installed but kwcolumns no recognised

### ISSUE THREAD

**Issue by boardtc** [dwp-forge/columns#8]
My dokuwiki has been down for a long time after a cPanel restore did not work out. I've an [ongoing query](https://forum.dokuwiki.org/d/18596-restoring-cpanel-with-farm) on the forum.

When I go to my site I get a parse error straight away so I can't get into DokuWiki
syntax error, unexpected 'kwcolumns' (T_STRING) in /home/mysite/public_html/dokuwiki/lib/plugins/columns/lang/en/lang.php on line 19

I know kwcolumns is from your plugin. Do you have any thoughts that might help?

**Comment by dwp-forge** [comment]
The screenshot you provided on the forum shows [settings.php](https://github.com/dwp-forge/columns/blob/master/lang/en/settings.php) and [lang.php](https://github.com/dwp-forge/columns/blob/master/lang/en/lang.php) merged into one file. Try to reinstall the plugin.

**Comment by boardtc** [comment]
Sorry about that, my bad editing, I fixed that, they are not merged.
I am not able to get into DokuWiki to do anything (like installing a plugin) :-(

**Comment by boardtc** [comment]
I updated the plugin and the [original post](https://forum.dokuwiki.org/d/18596-restoring-cpanel-with-farm/5) as I thought there might be more traffic over there. Not sure if it's this plugin that's causing the problem....

**Comment by dwp-forge** [comment]
Not sure what you mean by "putting one image after another", but on the editor screenshot you can clearly see the problem in your local lang.php.

![image](https://user-images.githubusercontent.com/11460562/153091822-b0f50390-e8ce-4760-a3a5-140846294453.png)

I  have no idea how you got to that state, but with this level of file system corruption all bets are off. Literally anything go wrong.

**Comment by boardtc** [comment]
Thanks for helping me. It sounds like we got out wires crossed. I spaced the images so they did not look like they were merged but you were meaning something else. Now however I have overwritten your lang.php with the new version. Not sure what to do now :-(
